//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tekra.FEL
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/", ConfigurationName="Tekra.FEL.KTFCertificador")]
    public interface KTFCertificador
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/CertificacionDo" +
            "cumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Tekra.FEL.CertificacionDocumentoResponse1> CertificacionDocumentoAsync(Tekra.FEL.CertificacionDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/AnulacionDocume" +
            "nto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Tekra.FEL.AnulacionDocumentoResponse1> AnulacionDocumentoAsync(Tekra.FEL.AnulacionDocumentoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/")]
    public partial class CertificacionDocumento
    {
        
        private AutenticacionCertificacion autenticacionField;
        
        private string documentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AutenticacionCertificacion Autenticacion
        {
            get
            {
                return this.autenticacionField;
            }
            set
            {
                this.autenticacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/")]
    public partial class AutenticacionCertificacion
    {
        
        private string pn_usuarioField;
        
        private string pn_claveField;
        
        private long pn_clienteField;
        
        private long pn_contratoField;
        
        private string pn_id_origenField;
        
        private string pn_ip_origenField;
        
        private string pn_firmar_emisorField;
        
        private string pn_validar_identificadorField;
        
        private string pn_retornar_pdfField;
        
        private string pn_reemplazar_receptorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pn_usuario
        {
            get
            {
                return this.pn_usuarioField;
            }
            set
            {
                this.pn_usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pn_clave
        {
            get
            {
                return this.pn_claveField;
            }
            set
            {
                this.pn_claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long pn_cliente
        {
            get
            {
                return this.pn_clienteField;
            }
            set
            {
                this.pn_clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long pn_contrato
        {
            get
            {
                return this.pn_contratoField;
            }
            set
            {
                this.pn_contratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string pn_id_origen
        {
            get
            {
                return this.pn_id_origenField;
            }
            set
            {
                this.pn_id_origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pn_ip_origen
        {
            get
            {
                return this.pn_ip_origenField;
            }
            set
            {
                this.pn_ip_origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string pn_firmar_emisor
        {
            get
            {
                return this.pn_firmar_emisorField;
            }
            set
            {
                this.pn_firmar_emisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string pn_validar_identificador
        {
            get
            {
                return this.pn_validar_identificadorField;
            }
            set
            {
                this.pn_validar_identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string pn_retornar_pdf
        {
            get
            {
                return this.pn_retornar_pdfField;
            }
            set
            {
                this.pn_retornar_pdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pn_reemplazar_receptor
        {
            get
            {
                return this.pn_reemplazar_receptorField;
            }
            set
            {
                this.pn_reemplazar_receptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/")]
    public partial class AutenticacionAnulacion
    {
        
        private string pn_usuarioField;
        
        private string pn_claveField;
        
        private long pn_clienteField;
        
        private long pn_contratoField;
        
        private string pn_firmar_emisorField;
        
        private string pn_retornar_pdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pn_usuario
        {
            get
            {
                return this.pn_usuarioField;
            }
            set
            {
                this.pn_usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pn_clave
        {
            get
            {
                return this.pn_claveField;
            }
            set
            {
                this.pn_claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long pn_cliente
        {
            get
            {
                return this.pn_clienteField;
            }
            set
            {
                this.pn_clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long pn_contrato
        {
            get
            {
                return this.pn_contratoField;
            }
            set
            {
                this.pn_contratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string pn_firmar_emisor
        {
            get
            {
                return this.pn_firmar_emisorField;
            }
            set
            {
                this.pn_firmar_emisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pn_retornar_pdf
        {
            get
            {
                return this.pn_retornar_pdfField;
            }
            set
            {
                this.pn_retornar_pdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/")]
    public partial class CertificacionDocumentoResponse
    {
        
        private string resultadoCertificacionField;
        
        private string documentoCertificadoField;
        
        private string representacionGraficaField;
        
        private string codigoQRField;
        
        private string nITCertificadorField;
        
        private string nombreCertificadorField;
        
        private string numeroAutorizacionField;
        
        private string numeroDocumentoField;
        
        private string serieDocumentoField;
        
        private string fechaHoraEmisionField;
        
        private string fechaHoraCertificacionField;
        
        private string nombreReceptorField;
        
        private string estadoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResultadoCertificacion
        {
            get
            {
                return this.resultadoCertificacionField;
            }
            set
            {
                this.resultadoCertificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocumentoCertificado
        {
            get
            {
                return this.documentoCertificadoField;
            }
            set
            {
                this.documentoCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RepresentacionGrafica
        {
            get
            {
                return this.representacionGraficaField;
            }
            set
            {
                this.representacionGraficaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CodigoQR
        {
            get
            {
                return this.codigoQRField;
            }
            set
            {
                this.codigoQRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NITCertificador
        {
            get
            {
                return this.nITCertificadorField;
            }
            set
            {
                this.nITCertificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NombreCertificador
        {
            get
            {
                return this.nombreCertificadorField;
            }
            set
            {
                this.nombreCertificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NumeroAutorizacion
        {
            get
            {
                return this.numeroAutorizacionField;
            }
            set
            {
                this.numeroAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=7)]
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SerieDocumento
        {
            get
            {
                return this.serieDocumentoField;
            }
            set
            {
                this.serieDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FechaHoraEmision
        {
            get
            {
                return this.fechaHoraEmisionField;
            }
            set
            {
                this.fechaHoraEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string FechaHoraCertificacion
        {
            get
            {
                return this.fechaHoraCertificacionField;
            }
            set
            {
                this.fechaHoraCertificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string NombreReceptor
        {
            get
            {
                return this.nombreReceptorField;
            }
            set
            {
                this.nombreReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string EstadoDocumento
        {
            get
            {
                return this.estadoDocumentoField;
            }
            set
            {
                this.estadoDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CertificacionDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/", Order=0)]
        public Tekra.FEL.CertificacionDocumento CertificacionDocumento;
        
        public CertificacionDocumentoRequest()
        {
        }
        
        public CertificacionDocumentoRequest(Tekra.FEL.CertificacionDocumento CertificacionDocumento)
        {
            this.CertificacionDocumento = CertificacionDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CertificacionDocumentoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/", Order=0)]
        public Tekra.FEL.CertificacionDocumentoResponse CertificacionDocumentoResponse;
        
        public CertificacionDocumentoResponse1()
        {
        }
        
        public CertificacionDocumentoResponse1(Tekra.FEL.CertificacionDocumentoResponse CertificacionDocumentoResponse)
        {
            this.CertificacionDocumentoResponse = CertificacionDocumentoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/")]
    public partial class AnulacionDocumento
    {
        
        private AutenticacionAnulacion autenticacionField;
        
        private string documentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AutenticacionAnulacion Autenticacion
        {
            get
            {
                return this.autenticacionField;
            }
            set
            {
                this.autenticacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/")]
    public partial class AnulacionDocumentoResponse
    {
        
        private string resultadoAnulacionField;
        
        private string anulacionCertificadaField;
        
        private string representacionGraficaField;
        
        private string codigoQRField;
        
        private string nITCertificadorField;
        
        private string nombreCertificadorField;
        
        private string numeroAutorizacionField;
        
        private string numeroDocumentoField;
        
        private string serieDocumentoField;
        
        private string fechaHoraEmisionField;
        
        private string fechaHoraCertificacionField;
        
        private string estadoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResultadoAnulacion
        {
            get
            {
                return this.resultadoAnulacionField;
            }
            set
            {
                this.resultadoAnulacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AnulacionCertificada
        {
            get
            {
                return this.anulacionCertificadaField;
            }
            set
            {
                this.anulacionCertificadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RepresentacionGrafica
        {
            get
            {
                return this.representacionGraficaField;
            }
            set
            {
                this.representacionGraficaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CodigoQR
        {
            get
            {
                return this.codigoQRField;
            }
            set
            {
                this.codigoQRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NITCertificador
        {
            get
            {
                return this.nITCertificadorField;
            }
            set
            {
                this.nITCertificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NombreCertificador
        {
            get
            {
                return this.nombreCertificadorField;
            }
            set
            {
                this.nombreCertificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NumeroAutorizacion
        {
            get
            {
                return this.numeroAutorizacionField;
            }
            set
            {
                this.numeroAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=7)]
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SerieDocumento
        {
            get
            {
                return this.serieDocumentoField;
            }
            set
            {
                this.serieDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FechaHoraEmision
        {
            get
            {
                return this.fechaHoraEmisionField;
            }
            set
            {
                this.fechaHoraEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string FechaHoraCertificacion
        {
            get
            {
                return this.fechaHoraCertificacionField;
            }
            set
            {
                this.fechaHoraCertificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string EstadoDocumento
        {
            get
            {
                return this.estadoDocumentoField;
            }
            set
            {
                this.estadoDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnulacionDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/", Order=0)]
        public Tekra.FEL.AnulacionDocumento AnulacionDocumento;
        
        public AnulacionDocumentoRequest()
        {
        }
        
        public AnulacionDocumentoRequest(Tekra.FEL.AnulacionDocumento AnulacionDocumento)
        {
            this.AnulacionDocumento = AnulacionDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnulacionDocumentoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://apicertificacion.desa.tekra.com.gt:8080/certificacion/wsdl/", Order=0)]
        public Tekra.FEL.AnulacionDocumentoResponse AnulacionDocumentoResponse;
        
        public AnulacionDocumentoResponse1()
        {
        }
        
        public AnulacionDocumentoResponse1(Tekra.FEL.AnulacionDocumentoResponse AnulacionDocumentoResponse)
        {
            this.AnulacionDocumentoResponse = AnulacionDocumentoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface KTFCertificadorChannel : Tekra.FEL.KTFCertificador, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class KTFCertificadorClient : System.ServiceModel.ClientBase<Tekra.FEL.KTFCertificador>, Tekra.FEL.KTFCertificador
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KTFCertificadorClient() : 
                base(KTFCertificadorClient.GetDefaultBinding(), KTFCertificadorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.KTFCertificadorSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KTFCertificadorClient(EndpointConfiguration endpointConfiguration) : 
                base(KTFCertificadorClient.GetBindingForEndpoint(endpointConfiguration), KTFCertificadorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KTFCertificadorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KTFCertificadorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KTFCertificadorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KTFCertificadorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KTFCertificadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tekra.FEL.CertificacionDocumentoResponse1> Tekra.FEL.KTFCertificador.CertificacionDocumentoAsync(Tekra.FEL.CertificacionDocumentoRequest request)
        {
            return base.Channel.CertificacionDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tekra.FEL.CertificacionDocumentoResponse1> CertificacionDocumentoAsync(Tekra.FEL.CertificacionDocumento CertificacionDocumento)
        {
            Tekra.FEL.CertificacionDocumentoRequest inValue = new Tekra.FEL.CertificacionDocumentoRequest();
            inValue.CertificacionDocumento = CertificacionDocumento;
            return ((Tekra.FEL.KTFCertificador)(this)).CertificacionDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tekra.FEL.AnulacionDocumentoResponse1> Tekra.FEL.KTFCertificador.AnulacionDocumentoAsync(Tekra.FEL.AnulacionDocumentoRequest request)
        {
            return base.Channel.AnulacionDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tekra.FEL.AnulacionDocumentoResponse1> AnulacionDocumentoAsync(Tekra.FEL.AnulacionDocumento AnulacionDocumento)
        {
            Tekra.FEL.AnulacionDocumentoRequest inValue = new Tekra.FEL.AnulacionDocumentoRequest();
            inValue.AnulacionDocumento = AnulacionDocumento;
            return ((Tekra.FEL.KTFCertificador)(this)).AnulacionDocumentoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KTFCertificadorSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KTFCertificadorSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://apicertificacion.desa.tekra.com.gt:8080/certificacion/servicio.php");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KTFCertificadorClient.GetBindingForEndpoint(EndpointConfiguration.KTFCertificadorSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KTFCertificadorClient.GetEndpointAddress(EndpointConfiguration.KTFCertificadorSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            KTFCertificadorSOAP,
        }
    }
}
